#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DiaCont.Resource", IsApplication=true)]

namespace DiaCont
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::DiaCont.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::DiaCont.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int azul = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int azulclaro = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int cinza = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int facebook1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int facebook2 = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int rounded_edit_text = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rounded_edit_text2 = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int bttdeletar = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int btteditar = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int button1 = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int checkBox1 = 2131099655;
			
			// aapt resource value: 0x7f060018
			public const int dataCampo = 2131099672;
			
			// aapt resource value: 0x7f06001c
			public const int enderecoCampo = 2131099676;
			
			// aapt resource value: 0x7f060016
			public const int eventoCampo = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int horarioCampo = 2131099674;
			
			// aapt resource value: 0x7f06001e
			public const int item_subtitle = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int item_title = 2131099679;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout2 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout3 = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int loginLoginButton = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int loginLoginCampo = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int loginSenhaButton = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int loginSenhaCampo = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int loginSlogan = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int loginTitulo = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int login_layout = 2131099659;
			
			// aapt resource value: 0x7f060017
			public const int novaData = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int novaEndereco = 2131099675;
			
			// aapt resource value: 0x7f060015
			public const int novaEvento = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int novaHorario = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int novaTitulo = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int nova_layout = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int novaconfirmarButton = 2131099677;
			
			// aapt resource value: 0x7f060012
			public const int registrar = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int sliding_tabs = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int textView3 = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int viewpager = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int alterar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int excluir = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_sample = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int nova = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int pager_item = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int confirmar = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int data = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int endereco = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int evento = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int horario = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int login = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int loginFacebook = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int nome = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int registrar = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int sair = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int senha = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int slogan = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int titulo_nova = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
